---

  - name: Copy sudoers file to /etc/sudoers.tmp (and kept here for later change checks)
    action: template src=../templates/sudoers dest=/etc/sudoers.tmp mode=440 owner=root group=root
    register: sudoers_copy_result
    sudo: yes

  - name: Install /etc/sudoers file (and fail if invalid)
    action: shell visudo -q -c -f /etc/sudoers.tmp && cp /etc/sudoers.tmp /etc/sudoers
    when: sudoers_copy_result.changed
    sudo: yes

